import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-reverse-logistics-vendor-credit-recovery",
  "engine": "recovery",
  "title": "Reverse Logistics & Vendor Credit Recovery",
  "shortTitle": "Vendor Credit Recovery",
  "tagline": "Ensure every authorized return becomes a complete, timely, and correctly valued vendor credit",
  "industry": "Returns Financial Operations",
  "uiPort": 4585,
  "apiPort": 5585,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Missing, partial, and delayed return credits recovered with serialized custody and policy evidence",
  "valueNarrative": "Track return authorizations, SKUs, serials, shipments, vendor receipts, restocking, warranties, recalls, cores, credit memos, and GL posting.",
  "calculation": {
    "actualKey": "receivedCredit",
    "expectedKey": "expectedCredit",
    "actualLabel": "Received Vendor Credit",
    "expectedLabel": "Expected Return Credit",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Return authorization, shipment custody, vendor receipt, and policy evidence indicate missing vendor credit.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("vendor-return-policy-library","VCR01","Vendor return-policy library","Reconcile vendor return-policy library using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed vendor return-policy library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Vendor return-policy library Reference","text","VCR01-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("return-authorization-registry","VCR02","Return authorization registry","Reconcile return authorization registry using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed return authorization registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Return authorization registry Reference","text","VCR02-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("sku-and-serial-tracking","VCR03","SKU and serial tracking","Reconcile sku and serial tracking using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed sku and serial tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","SKU and serial tracking Reference","text","VCR03-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("return-shipment-generation","VCR04","Return shipment generation","Reconcile return shipment generation using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed return shipment generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Return shipment generation Reference","text","VCR04-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("carrier-delivery-evidence","VCR05","Carrier delivery evidence","Reconcile carrier delivery evidence using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed carrier delivery evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Carrier delivery evidence Reference","text","VCR05-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("vendor-receipt-confirmation","VCR06","Vendor receipt confirmation","Reconcile vendor receipt confirmation using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed vendor receipt confirmation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Vendor receipt confirmation Reference","text","VCR06-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("expected-credit-calculation","VCR07","Expected credit calculation","Reconcile expected credit calculation using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed expected credit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Expected credit calculation Reference","text","VCR07-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("restocking-fee-validation","VCR08","Restocking fee validation","Reconcile restocking fee validation using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed restocking fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Restocking fee validation Reference","text","VCR08-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("warranty-credit-validation","VCR09","Warranty credit validation","Reconcile warranty credit validation using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed warranty credit validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Warranty credit validation Reference","text","VCR09-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("recall-credit-reconciliation","VCR10","Recall credit reconciliation","Reconcile recall credit reconciliation using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed recall credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Recall credit reconciliation Reference","text","VCR10-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("core-and-deposit-recovery","VCR11","Core and deposit recovery","Reconcile core and deposit recovery using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed core and deposit recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Core and deposit recovery Reference","text","VCR11-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("missing-credit-detection","VCR12","Missing-credit detection","Reconcile missing-credit detection using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed missing-credit detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Missing-credit detection Reference","text","VCR12-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("vendor-inquiry-workflow","VCR13","Vendor inquiry workflow","Reconcile vendor inquiry workflow using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed vendor inquiry workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Vendor inquiry workflow Reference","text","VCR13-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("credit-memo-matching","VCR14","Credit memo matching","Reconcile credit memo matching using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed credit memo matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Credit memo matching Reference","text","VCR14-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("general-ledger-reconciliation","VCR15","General-ledger reconciliation","Reconcile general-ledger reconciliation using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed general-ledger reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","General-ledger reconciliation Reference","text","VCR15-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]}),
feature("vendor-and-sku-recovery-analytics","VCR16","Vendor and SKU recovery analytics","Reconcile vendor and sku recovery analytics using vendor return policies, RMAs, SKU and serial records, return shipments, carrier delivery, vendor receipts, restocking terms, warranties, recalls, cores, credit memos, and GL entries.","Produce a governed vendor and sku recovery analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendorReturn","Vendor / Return Authorization","text","Summit Components / RMA-884120"],["caseReference","Vendor and SKU recovery analytics Reference","text","VCR16-2026-001"],["receivedCredit","Received Vendor Credit","currency",742000],["expectedCredit","Expected Return Credit","currency",886500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredit",subjects:["Defective component return","Excess inventory return","Recall return","Core deposit return","Warranty return"]})
]);
